// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPq84MgB7N46NHAqbrwOsTl-QO6RG5v5w',
    appId: '1:834052870681:web:454d897130ca70dd27d088',
    messagingSenderId: '834052870681',
    projectId: 'my-portfolio-c56e8',
    authDomain: 'my-portfolio-c56e8.firebaseapp.com',
    storageBucket: 'my-portfolio-c56e8.firebasestorage.app',
    measurementId: 'G-RJ2DQ7495D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Vp9WYt9nt0ZTWgHhSp_FcrSRZ_ja79g',
    appId: '1:834052870681:android:dc758c4a02ded40c27d088',
    messagingSenderId: '834052870681',
    projectId: 'my-portfolio-c56e8',
    storageBucket: 'my-portfolio-c56e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKrrFzd8gIDA2ZX7eUc0AwNJA8oGC4IO4',
    appId: '1:834052870681:ios:8418ad8fccc7f16a27d088',
    messagingSenderId: '834052870681',
    projectId: 'my-portfolio-c56e8',
    storageBucket: 'my-portfolio-c56e8.firebasestorage.app',
    iosBundleId: 'com.example.myPrtofolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKrrFzd8gIDA2ZX7eUc0AwNJA8oGC4IO4',
    appId: '1:834052870681:ios:8418ad8fccc7f16a27d088',
    messagingSenderId: '834052870681',
    projectId: 'my-portfolio-c56e8',
    storageBucket: 'my-portfolio-c56e8.firebasestorage.app',
    iosBundleId: 'com.example.myPrtofolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPq84MgB7N46NHAqbrwOsTl-QO6RG5v5w',
    appId: '1:834052870681:web:78cdbeb3377ad83c27d088',
    messagingSenderId: '834052870681',
    projectId: 'my-portfolio-c56e8',
    authDomain: 'my-portfolio-c56e8.firebaseapp.com',
    storageBucket: 'my-portfolio-c56e8.firebasestorage.app',
    measurementId: 'G-W5FHVG3G88',
  );
}
